name: appinio_social_share_plus
description: Supports sharing text, images, files and text with image to social media (Facebook, Instagram, Instagram Story, Messenger, Telegram, WhatsApp, Twitter, Tiktok, SMS, System, etc.).
version: 0.4.1
homepage: https://github.com/wonoyu/appinio_flutter_packages/tree/main/packages/appinio_social_share_plus
repository: https://github.com/wonoyu/appinio_flutter_packages/tree/main/packages/appinio_social_share_plus

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  html2md: ^1.3.2
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.appinio.socialshare.appinio_social_share
        pluginClass: AppinioSocialSharePlugin
      ios:
        pluginClass: AppinioSocialSharePlugin
